// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfRfeP6FhMfMZycZHsQj8E5uImdEGDLIA',
    appId: '1:681957771399:web:9138d7c6d5ae98a16f9022',
    messagingSenderId: '681957771399',
    projectId: 'peeisstoredintheballs-be357',
    authDomain: 'peeisstoredintheballs-be357.firebaseapp.com',
    storageBucket: 'peeisstoredintheballs-be357.appspot.com',
    measurementId: 'G-VRZBR7SK1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHOuWw23cKNkGy5ToafE7xrdsJuvhyorY',
    appId: '1:681957771399:android:b723c97ab3db3be16f9022',
    messagingSenderId: '681957771399',
    projectId: 'peeisstoredintheballs-be357',
    storageBucket: 'peeisstoredintheballs-be357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEAOpEf5WS2KRd5kfqESlfEQ6Qhbz63yc',
    appId: '1:681957771399:ios:eceac6d5d397fe656f9022',
    messagingSenderId: '681957771399',
    projectId: 'peeisstoredintheballs-be357',
    storageBucket: 'peeisstoredintheballs-be357.appspot.com',
    iosClientId: '681957771399-ndbl2pm41urjaj3uvj3u8fs2jtaok391.apps.googleusercontent.com',
    iosBundleId: 'com.example.corner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEAOpEf5WS2KRd5kfqESlfEQ6Qhbz63yc',
    appId: '1:681957771399:ios:eceac6d5d397fe656f9022',
    messagingSenderId: '681957771399',
    projectId: 'peeisstoredintheballs-be357',
    storageBucket: 'peeisstoredintheballs-be357.appspot.com',
    iosClientId: '681957771399-ndbl2pm41urjaj3uvj3u8fs2jtaok391.apps.googleusercontent.com',
    iosBundleId: 'com.example.corner',
  );
}
