// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVa9V9SM0HOF3kzc6YMxEY3gnfoNbdEcs',
    appId: '1:824965475652:web:b43c1fb9f1116e64017b11',
    messagingSenderId: '824965475652',
    projectId: 'peeisstoredintheballs2',
    authDomain: 'peeisstoredintheballs2.firebaseapp.com',
    storageBucket: 'peeisstoredintheballs2.appspot.com',
    measurementId: 'G-N40Z14WMHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg5bYx0xc2BRCmaAcRdF36CpO3cizi4zQ',
    appId: '1:824965475652:android:76cc639b32b9ba65017b11',
    messagingSenderId: '824965475652',
    projectId: 'peeisstoredintheballs2',
    storageBucket: 'peeisstoredintheballs2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK5X2Fs1E32pBDi0C_uHeV7XlgScU-0P8',
    appId: '1:824965475652:ios:40a25b9e609043fa017b11',
    messagingSenderId: '824965475652',
    projectId: 'peeisstoredintheballs2',
    storageBucket: 'peeisstoredintheballs2.appspot.com',
    iosClientId: '824965475652-dd89shefhdci0rm1tqmd5m3esjurf96p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK5X2Fs1E32pBDi0C_uHeV7XlgScU-0P8',
    appId: '1:824965475652:ios:40a25b9e609043fa017b11',
    messagingSenderId: '824965475652',
    projectId: 'peeisstoredintheballs2',
    storageBucket: 'peeisstoredintheballs2.appspot.com',
    iosClientId: '824965475652-dd89shefhdci0rm1tqmd5m3esjurf96p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo1',
  );
}
