// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaTCzXvv2a8z_s8ct1DF46GEMzZNgTVAU',
    appId: '1:345942178681:web:ff2c414f6f635315750da8',
    messagingSenderId: '345942178681',
    projectId: 'chatapp-27faf',
    authDomain: 'chatapp-27faf.firebaseapp.com',
    storageBucket: 'chatapp-27faf.appspot.com',
    measurementId: 'G-SC96L64FMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8bNukqGtfMOQJggGXC8v018z2RV2qdZ8',
    appId: '1:345942178681:android:b3ba6b3fe3a8cadb750da8',
    messagingSenderId: '345942178681',
    projectId: 'chatapp-27faf',
    storageBucket: 'chatapp-27faf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZHHXk0K61xKlMeDXSG6FfDcUdq55NTaQ',
    appId: '1:345942178681:ios:e19b5669656f4364750da8',
    messagingSenderId: '345942178681',
    projectId: 'chatapp-27faf',
    storageBucket: 'chatapp-27faf.appspot.com',
    iosClientId: '345942178681-mg8223a48inifudcsmugel0thefbn5rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZHHXk0K61xKlMeDXSG6FfDcUdq55NTaQ',
    appId: '1:345942178681:ios:e19b5669656f4364750da8',
    messagingSenderId: '345942178681',
    projectId: 'chatapp-27faf',
    storageBucket: 'chatapp-27faf.appspot.com',
    iosClientId: '345942178681-mg8223a48inifudcsmugel0thefbn5rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
