// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAie0v2Al4siDJTIYNf1vedLw3S54TitdI',
    appId: '1:24036376102:web:a154b1bbb5f970eaeff0e7',
    messagingSenderId: '24036376102',
    projectId: 'africanwater-68f12',
    authDomain: 'africanwater-68f12.firebaseapp.com',
    databaseURL: 'https://africanwater-68f12-default-rtdb.firebaseio.com',
    storageBucket: 'africanwater-68f12.appspot.com',
    measurementId: 'G-EFV5XNE7VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrJ12V7GV_dn-SulefHjfJ8qkXnHGN0rw',
    appId: '1:24036376102:android:be752d97deae4012eff0e7',
    messagingSenderId: '24036376102',
    projectId: 'africanwater-68f12',
    databaseURL: 'https://africanwater-68f12-default-rtdb.firebaseio.com',
    storageBucket: 'africanwater-68f12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-2vwPtxs3Kp5WT_71JTvUAIkdvzm2js',
    appId: '1:24036376102:ios:90457a4dc6e03baceff0e7',
    messagingSenderId: '24036376102',
    projectId: 'africanwater-68f12',
    databaseURL: 'https://africanwater-68f12-default-rtdb.firebaseio.com',
    storageBucket: 'africanwater-68f12.appspot.com',
    iosClientId: '24036376102-no485a22tv3u3cq35v65mpio3meunn86.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW-2vwPtxs3Kp5WT_71JTvUAIkdvzm2js',
    appId: '1:24036376102:ios:90457a4dc6e03baceff0e7',
    messagingSenderId: '24036376102',
    projectId: 'africanwater-68f12',
    databaseURL: 'https://africanwater-68f12-default-rtdb.firebaseio.com',
    storageBucket: 'africanwater-68f12.appspot.com',
    iosClientId: '24036376102-no485a22tv3u3cq35v65mpio3meunn86.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
