// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWhw5-oMp2FnvamYkh-I8i2Q7g0VQrd_I',
    appId: '1:500777746769:web:13b17f5ce1014f2f755370',
    messagingSenderId: '500777746769',
    projectId: 'login-28813',
    authDomain: 'login-28813.firebaseapp.com',
    storageBucket: 'login-28813.appspot.com',
    measurementId: 'G-BM5JLY9HWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDevVmn-5nsMGVUnRU-eYCd24-aLoaj67g',
    appId: '1:500777746769:android:8a3c6ba5a1a6a1fa755370',
    messagingSenderId: '500777746769',
    projectId: 'login-28813',
    storageBucket: 'login-28813.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA87XGcoWqAqudrZzKC9oJJvVTxbLZbdog',
    appId: '1:500777746769:ios:0a57f4f010ceb81d755370',
    messagingSenderId: '500777746769',
    projectId: 'login-28813',
    storageBucket: 'login-28813.appspot.com',
    iosClientId: '500777746769-ekf5q6gh0nv2763hsun16m4kne4r4kna.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA87XGcoWqAqudrZzKC9oJJvVTxbLZbdog',
    appId: '1:500777746769:ios:0a57f4f010ceb81d755370',
    messagingSenderId: '500777746769',
    projectId: 'login-28813',
    storageBucket: 'login-28813.appspot.com',
    iosClientId: '500777746769-ekf5q6gh0nv2763hsun16m4kne4r4kna.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
