// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAleEsvTjV5AqEux3SOl_pKEyye930U5TE',
    appId: '1:30436198948:web:914726a6de3969ca7066b1',
    messagingSenderId: '30436198948',
    projectId: 'svhsp-ee9ee',
    authDomain: 'svhsp-ee9ee.firebaseapp.com',
    storageBucket: 'svhsp-ee9ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe5Gc6q3Ox2ncJvY6rVsdhu32zHFxfoE4',
    appId: '1:30436198948:android:d796f28506c33ad97066b1',
    messagingSenderId: '30436198948',
    projectId: 'svhsp-ee9ee',
    storageBucket: 'svhsp-ee9ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHETrVYhr9j5vJg-RQTYDMStROsKvGsuE',
    appId: '1:30436198948:ios:73ba9472eec73e567066b1',
    messagingSenderId: '30436198948',
    projectId: 'svhsp-ee9ee',
    storageBucket: 'svhsp-ee9ee.appspot.com',
    iosClientId: '30436198948-3041ci7rgp80jcihb13adfkttc1oi25l.apps.googleusercontent.com',
    iosBundleId: 'com.example.teachingAtSvhsp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHETrVYhr9j5vJg-RQTYDMStROsKvGsuE',
    appId: '1:30436198948:ios:73ba9472eec73e567066b1',
    messagingSenderId: '30436198948',
    projectId: 'svhsp-ee9ee',
    storageBucket: 'svhsp-ee9ee.appspot.com',
    iosClientId: '30436198948-3041ci7rgp80jcihb13adfkttc1oi25l.apps.googleusercontent.com',
    iosBundleId: 'com.example.teachingAtSvhsp',
  );
}
